### ISSUE TITLE
MEMORANDUM

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#13]
We now have 
- Positioning + Orientation + Ignore (+ other computation tweaks if needed)
- Small displacements

We will soon have
- Figure error (I will write a dedicated issue on that)
- we still miss Roughness (I have to fix sutf at LibWiser level)

We have to discuss on how to handle
- plots (in an organic way)

We need to ask Luca
- on broadcasting errors
- on tooltips
- on preinputs

The plan is
1) Do some quick test that Positioning+Displacement is working (we can improve plotting if this is required)
2) Implement Figure error and check it works (it is already done)
3) Implement Roughness

To do 1) I would create a prototype beamline. Here I have one with both V and H elements. I have put into edlettradrive\Examples2020\Milestone\Test Beamlines the file
beamline_layout_fel2_ldm_vh.py (also atteched here as *.txt). 

Se you if you prefer to have a "complete" test file, or a "simple" test file + a "sophisticated one".

For the simple one, I would pick up : source+pm2a+slits_h+kb_h+detector_h.

The complete one has mixed H/V elements 

```
Beamline.Append(s)  # source
Beamline.Append(pm2a) # plane mirror (H)
Beamline.Append(presto) # a grating, but in practice it is another plane mirror (H)
Beamline.Append(slits_v) # slits, V
Beamline.Append(slits_h) # slits, H
Beamline.Append(kb_v) # focussing mirror, V
Beamline.Append(kb_h) # focussing mirror, H
Beamline.Append(Detector_h)# detector h
Beamline.Append(Detector_v)# detector v
Beamline.RefreshPositions()
```
I would start as follow 
"TASK"
a) Start in the simplest configuration possible: compute only 1 orientation, considering only source, focussing and detector (other optical elements set to Ignore = True). Then check the other orientation as well. We should get a nice focussed spot.
b) Always with one orientation only, let's add the other optical elements (other otpical elements set to Ignore = False). It should work
c) Let's do it all-toghether!

If it works, everyithin is well piped and we can really go on on more tough ground.

At this level we can do another small test.
Go back to the same condition of a) (a single orientation, no extra optical elements), and let's try to use small displacement on the detector. If you shift it (of 1mm let's say) you should observe variation in the spot size.

This only to do some "fast tests". Extensive testing of the gui will be done by us.

If we do all these simulations at 20 nm, you  can safely use 5000 points I would say.

Please, write any comments if you feel I left out something or possibly gave an unprecise reference on what we agreed.

**Comment by aljosahafner** [comment]
This (sans Figure error) might be ready by tomorrow or early next week.

**Comment by capitanevs** [comment]
Updates 
1) **Errors**
We will catch errors at widget level (see old wise for example) and use QMessageBox to pop up in oasys. I write a more specific answer on issue #10

 2) **Tooltips**
He gave me this code token. Can it be helpful enough?
`oasysgui.lineEdit(left_box_1, self, "number_of_rays", "Number of Rays", tooltip="Number of Rays", labelWidth=260, valueType=int, orientation="horizontal")`
