### ISSUE TITLE
Unknown PD bug

### ISSUE THREAD

**Issue by aljosahafner** [oasys-elettra-kit/OASYS1-Wiser#21]
I think the last-appended O. E. gets correctly positioned, but somehow its position is wrongly reported by `__disp__` each time. This has to be investigated. This does not happen when scripting, only in the GUI.
When appending the next O. E., the distance for the previous gets corrected.

![image](https://user-images.githubusercontent.com/51963146/83402674-743b6f80-a407-11ea-8680-ffc3460b2bfd.png)

**Comment by aljosahafner** [comment]
Possible improvement of this would be:

1. Suppress the output to the console

2. Make a widget similar to Shadow `PostProcessor -> Info` for inspecting the beamline
![image](https://user-images.githubusercontent.com/51963146/89026665-62078000-d329-11ea-8335-30dbd4e79618.png)

**Comment by capitanevs** [comment]
I was about to get on this soon.
Is it fixed? Did you have to do something, or you have just realised that everything is working now?

**Comment by aljosahafner** [comment]
I don't know what is happening with this, but it seems that things work fine.

**Comment by capitanevs** [comment]
Ok, so we leave as conclusive comment:

it is working fine right now (without any dedicated action)
