### ISSUE TITLE
ALPHA - SERIOUS

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#25]
The chain of responsibility stopped working.
We have to investigate that AASAP

![immagine](https://user-images.githubusercontent.com/13431660/91547511-51e0c180-e924-11ea-9b51-eed4b40c9fee.png)

**General question:**
which version of LibWiser does Oasys use? Does it fish the info from GIT repository, or is there an intermediate step, where a "push" from GIT to another space is required? [I guess it is the second]

**Comment by aljosahafner** [comment]
This is the version: https://pypi.org/project/LibWiser/
It has to be updated manually each time when a new release is made (if there are newer requirements necessary). I don't know how to force OasysWiser to update LibWiser automatically as well. In setup.py (as you can see in the repository), such thing is reflected in line 46.

**Comment by capitanevs** [comment]
Debug notes:

for Michele:
path to LibWiser  (for oasys)
`C:\Users\Mike\Miniconda3\Lib\site-packages`

How to get to The Opticalelement

`in_object_1.wise_beamline.get_propagation_element(-1).get_optical_element().native_optical_element.Name`

**Comment by capitanevs** [comment]
After Meeting we concluded that

1) We need info from Luca on: "what is the best practice to make OASYS automatically update when LibWiser and WofryWiser are updated?"

2) The command
`print(in_object_1.wise_wavefront.wise_computation_result.Intensity)`,

called after the first mirror, returns NOT nan for Aljosa (which is correct), but returns [nan---nan] for Michele (which is weird). The N of Samples is correct. 

No clues about that for the moment.

3) **Apply** button and functionality is removed for the moment. => **How about the "Reference Field?"** apparently it does not make any sense right now. Let's keep it for the moment, but be prepared to hide it in the next future.

**Comment by aljosahafner** [comment]
Another bug or broken functionality, focus is not symmetric around 0:
![image](https://user-images.githubusercontent.com/51963146/91838156-4f94a500-ec4d-11ea-8565-b6865524f2e4.png)

**Comment by aljosahafner** [comment]
This is (luckily) not related to #27 , just wrong numbers

**Comment by capitanevs** [comment]
Random errors, but Aljosa solved it! B-)
