### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#39]
We have encountered problems with the units conversion.

An option could be eliminate it (but can we do that? Or is it something that Luca should do?)

Waiting more info from Michele:
if we use meters, is everything ok, or we still have problems?

**Comment by aljosahafner** [comment]
If we use meters I think everything is ok, at least I haven't encountered  issues

**Comment by capitanevs** [comment]
Question:
I have no prejudice against setting everything into meters. However there is something which is still not totally clear:
-How would it be related with OASYS from Luca? Is this a change that we are coordinating with Luca, or is it something that we would do on our own?
-Interaction between WISER and rest-of-the-world (SRW, SHADOW),  backcompatibility etc could present some issues?

**Comment by aljosahafner** [comment]
- He mentioned that it would be good to have everything in metres
- SRW is in metres, does not take into account OASYS built-in system for units. SHADOW is anyway raytracing.

**Comment by capitanevs** [comment]
Yeah, I remember you commented on Luca's point. But who is doing that? He or you? Will be the old *.ow files working with no problem? (I guess so, as he would not undertake such a decision).

**Comment by aljosahafner** [comment]
But SRW is already in metres, only SHADOW supports this feature (and now Wiser (not :) ))

**Comment by aljosahafner** [comment]
Should I go ahead with this - keep all units in m?

**Comment by capitanevs** [comment]
I double checked with Luca (I asked him some general clarification, all things you probably already knew).

Yes, let's go on!
We should improve the formatting for certain specific "sizes". For instance, using meters for the detector size is uncomfortable 
![immagine](https://user-images.githubusercontent.com/13431660/108982621-4a5d6380-768e-11eb-9eb3-75f5890b407d.png)
but if we could use scientific formatting (%0.2e, for example), I it would just be ok. The same for the slit size.

There is no general rule, but typically
- longitudinal distances are big numbers, so scientific notation might not be necessary
- *some* transverse lengths are small numbers (slit size, detector size), so exponential notation would help
- *other* transverse lenghts are in between (e.g. mirror lenght), so again scientific notation is not necessary.

how about that?

**Comment by aljosahafner** [comment]
I can investigate that, yes. We can also use another unit, such as mm or um (for slit size and/or size of detector).

I'll remove the unit switching...

**Comment by capitanevs** [comment]
The question is whether to hardcode the unit (um, mm, m) or give visual aid with the format.
If the second options is doable, I let's try with that. There are pros and cons in both cases. Let's take the more general one.


double check: You are going the unit switching only from wiser widget, right? So ShadowOUI will still be affected (as stated in the disclaimer) but all the rest of the world, not.

**Comment by aljosahafner** [comment]
It's just about WIser, it's all coded in each individual widget...

**Comment by capitanevs** [comment]
Allright. Let's go for it, if not gone yet.

**Comment by aljosahafner** [comment]
I removed the unit switcher entirely. I think with line edits it is not possible to change the display format to scientific. You can input in scientific format, e. g. 1e-6, but display will be in decimal numbers.

**Comment by capitanevs** [comment]
Subclassing PyQT classes (as Luca suggests) is not an option right now.

I don't know how you are settings the string in the text box. If you use the method setNum(), you can probably set the format

https://doc.qt.io/qt-5/qstring.html#setNum-9
(
![immagine](https://user-images.githubusercontent.com/13431660/109127126-5ad51300-774e-11eb-850a-fa4be4d9e3ea.png)

![immagine](https://user-images.githubusercontent.com/13431660/109127167-6b858900-774e-11eb-9dd6-84ff0db8f55b.png)

If you can get it through with that, good. It would be greatly reccomended, as no extra conversion code is necessary (with possible errors).
If not, let'sjust hardcode the units to save time.

**Comment by aljosahafner** [comment]
This has to be investigated a bit better, maybe with Luca. I did something, but my knowledge of (Py)Qt is not sufficient to make a bulletproof and nice solution.
