### ISSUE TITLE
M2 in Gaussian Source 

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#42]
It works for me, which probably means that there oasys is using an outdated version of LibWiser.

I have pulled the new one to master (rememember that master2 shall never be used)

If I run the script of the python script widget "test gaussian m2" with my Local version of LibWiser, I get:
![immagine](https://user-images.githubusercontent.com/13431660/109014476-768bdb00-76b4-11eb-8d37-824b006b891c.png)
(I have run the script twice, changing M2).

If run the widget, I always get this (no matter of M2 value)
![immagine](https://user-images.githubusercontent.com/13431660/109014614-97543080-76b4-11eb-8d05-5e6d6059ef09.png)

I guess that if that if LibWiser is updated, everything will be fine.

**Comment by aljosahafner** [comment]
* The widget is correctly linked to LibWiser
* LibWiser is now version 0.10.0. This is the current version of master
* I don't see any change in behaviour in Oasys

**Comment by capitanevs** [comment]
Very good, this means that I have not messed things up.
Thank you for checking!

I'll close the issue.
