### ISSUE TITLE
Figure Error - errors with Save/Restore

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#45]
Independently on Issue #44, the save/load command does not work with the figure error.
When loading a *.ow file, you will always find the default value
![immagine](https://user-images.githubusercontent.com/13431660/109016687-b18f0e00-76b6-11eb-93e7-4d65c7a0af76.png)

I would like to know more on how the save/load works, so that we both have an eye on that. Perhaps on next meeting would you share the code?

**Comment by aljosahafner** [comment]
It seems that #44 and this one are connected.
