### ISSUE TITLE
Figure Error - Problem with ReadXY/ReadLtpJave

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#46]
Reading the script in  "LtpJavaMode" or with "x, Height" does not work.
![immagine](https://user-images.githubusercontent.com/13431660/109024777-60831800-76be-11eb-83b4-52193b69804e.png)
I have put two scripts containing the right results.

**BEWARE**: they contained hardcoded paths. So just change them. We should do a unique python script delivering the main path to all the others (for debug purposes).

**Comment by aljosahafner** [comment]
`Height` appears the first time in LibWiser.Optics, line 2887. Everything seems fine in OASYS part.

**Comment by capitanevs** [comment]
And so? :-)
Let's try to boil down the problem. I have put a python script doing the job in the workspace. LibWiser alone can do the job. Why in OASYS it can not? Dowe have any clue?

**Comment by aljosahafner** [comment]
This is not replicable in versions 0.2.5 and 0.2.6

![image](https://user-images.githubusercontent.com/51963146/109299994-394f5680-7836-11eb-96dc-a82e57b6e058.png)

![image](https://user-images.githubusercontent.com/51963146/109300029-4a986300-7836-11eb-8a93-f313d250518d.png)

**Comment by capitanevs** [comment]
So what does it mean?
What is the differences between the new and the old version? LibWiser?

When closing issues, I usually leave some conclusive comments.
If something did not work and it is working now, it is still good to figure out what may have happened in between.:)

**Comment by aljosahafner** [comment]
Using the file `ldm-kbh/Scan_Motor5_56_res.dat` I get no error and everything works fine. I only tested using the two versions mentioned above. `0.2.5` is using an upgraded version of LibWiser - `0.10.0`. Maybe that's the reason.

**Comment by capitanevs** [comment]
Ok, let's take that as conclusive comment for this issue! :)

Tnx!
