### ISSUE TITLE
Source Gaussian => Visualization

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#47]
M2 is working now 
This means that by changing M2, the width of the Gaussian intensity changes **on a detector**

**However** the intensity plotted in the source widget is wrong and does not respond to any parameter settings.
Probably this is due to imperfect design by Luca.

**How to solve it**
Analytic sources does not really contain a propagated intensity to plot (unlike other numerical elements).
The previewed plot is just the gaussian function evaluated on a certain x axis at a certain distance z.

**Option 1** the easiest thing could be add two fields used for visualization only "x axis total length" and "z".
Something like that
![immagine](https://user-images.githubusercontent.com/13431660/111467345-a1ea6e80-8724-11eb-92ae-4928d2d0033a.png)

**Option 2**
Compute the intensity with
- z = GaussianSource.RayleighRange(...)  and 
- x = 4 * GaussianSource.Fwhm(z)
then write in the plot a meaningful title like "Intensity at the Rayleigh length = x.xm" (number properly formatted).

**just choose the faster one**

**Comment by aljosahafner** [comment]
1. I confirm, changing the parameters has no influence on the plot.
2. It is very easy to change
3. Going with option 2, I need to get a 1D matrix for each dimension, `x` and `z`, is there a function in `Optics.SourceGaussian`, that can do that?

**Comment by capitanevs** [comment]
You just need a 1d array fox the x. z is parameter.
you have to choose z = z_R (the Rayleigh Range of a Gaussian beam, delivered by the dedicated function)
and
x = linspace(-a,a,N)
where a must be large enough so that the entire function is visible.
It make sense  to take 'a' equal to the multiple of GaussianSource.Fwhm(z_R), for example
a= 4*Fwhm(z_R).
Just try

Remember: the plot title must be self-explainatory.
Example: "Intenisty at Rayleigh range ($z_R = XXX$)"

**For the formatting, let's start using the SmartFormatting functions.**

**Comment by capitanevs** [comment]
Here's how it works:
![immagine](https://user-images.githubusercontent.com/13431660/111627734-ab8cd880-87ef-11eb-9cc8-ae5de523dad5.png)


However, since the module Units is a little bit clumsy, we would better create an interface function in OASYS1-Wiser (for example, smart_format_number, or an equivalent meaningful name).

Here, you can add keywords parameters such as
UnitLetter => the unit of measurement, such as 'm' for meters
DisplayDigits => how many decimal digits to display

UnitLetter: just append it to the output of the LibWiser function
DisplayDigits: not necessary to implement it now. Just keep in mind for the future.

**Comment by capitanevs** [comment]
I will put this in a separate issue on formatting.

**Comment by aljosahafner** [comment]
All fine, I understand, but currently we are plotting a simple Gaussian PDF with centre and sigma. If there is anything more specific (with different normalization, etc.), then there has to be another function for plotting the shape.

**Comment by capitanevs** [comment]
We are plotting the intensity of  a Gaussian at a meaningful position of the gaussian beam (the Rayleigh range). The Gaussian function will (almost) look like the same, but what is changing is the Rayleigh Range (which is the reason why we have to add it to the plot title).

Yeah, that's tricky: we are painting the same "fixed" plot, but scales and distances are changing.

Do you get what I mean?

If the user want to explore how does the real gaussian intensity distribution look like at a certain z, he/she will use a detectorwidget.

What you have to plot is the Intensity, i.e. the squared value of the amplitude

![immagine](https://user-images.githubusercontent.com/13431660/111635839-3671d100-87f8-11eb-8c8a-aa5ad607a239.png)

**Comment by capitanevs** [comment]
r is your abscissa,
z must be the RayleighRange

**Comment by aljosahafner** [comment]
Implemented in v0.2.12
