### ISSUE TITLE
x axis in Find best focus

### ISSUE THREAD

**Issue by aljosahafner** [oasys-elettra-kit/OASYS1-Wiser#48]
![image](https://user-images.githubusercontent.com/51963146/111617675-b6da0700-87e3-11eb-8e4c-687ee41c905d.png)

Define the correct way to display x axis in Find best focus calculation. Now it is wrong! It would be best if function `Foundation.FindFocus` would return `S` as well.

**Comment by capitanevs** [comment]
Totally right.


I added the attribute "S" in the  Results:

![immagine](https://user-images.githubusercontent.com/13431660/111644660-54dbca80-8800-11eb-8ecd-b8301c9d3d62.png)

it should suite you

**Comment by capitanevs** [comment]
Pushed. Tell me if it works.

**Comment by aljosahafner** [comment]
Ok, great! It works.
![image](https://user-images.githubusercontent.com/51963146/111668173-c70ada00-8815-11eb-8328-f8d2f9664d65.png)
