### ISSUE TITLE
Formatting: let's make it smart

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#49]
Formatting numbers is a pain-in-the ass, especially while plotting.

We have to ensure that number formatting is visually acceptable:
1) when displaying single numbers
![immagine](https://user-images.githubusercontent.com/13431660/111633108-71bed080-87f5-11eb-94a4-b8cf771e2dff.png)

2) In plots, expecially on the X axis.

**How:**
1) Let's create an interface function in oasys1-wiser that wraps GetEngNumberSI. Example: `smart_format_number`
It should also contain a 'UnitLetter' (m for meters, C for Coulombs, etc).
It could contain a place holder for "DecimalDigits", that raises a NonImplementedError.

2) There are a lot of considerations to do.
- A good solution is to force scientific representation for both axes. This is done by means of `plt.ticklabel_format(axis="x", style="sci", scilimits=(0,0))` (see example below)
- An even better solution is to use SI formatting, e.g. 0.001 => 1m (1 milli-),
(see the code below, generating those figures)

![immagine](https://user-images.githubusercontent.com/13431660/111633892-42f52a00-87f6-11eb-9436-5125f161eb8f.png)
![immagine](https://user-images.githubusercontent.com/13431660/111634009-5dc79e80-87f6-11eb-99c8-e2ecb3ecdcdb.png)

I would do an interface function (e.g. `smart_format_plot`) that for now implements the good method, leaving the "even better" one for someone else.

Possible structure
```
def smart_format_plot(plot_handle, 
x_label ='', 
x_unit = '',
y_label = '',
y_unit = '',
title =''
)
```
labels and units are composed as `"%s [%s]" %(x_label, x_unit)`.

See you what's the best compared with the existing code.

**Example code**
```

# -*- coding: utf-8 -*-
"""
Created on Thu Mar 18 13:59:23 2021

@author: Mike
"""

#%%
import LibWiser.Units as Units
import numpy as np 
from  LibWiser.EasyGo import *


a = 1e-5
x = np.linspace(-a, a, 1000)
y = x**3
XUnitLetter = 'C' # Coulomb
XUnitName = 'Charge'
XSmartFormat = True


YUnitLetter = 'A'
YUnitName = 'Current'
YSmartFormat = True


plt.figure(1)
plot(x,y)
plt.title('afwul figure')

#%%
plt.figure(2)

plot(x,y)
plt.ticklabel_format(axis="x", style="sci", scilimits=(0,0))
plt.ticklabel_format(axis="y", style="sci", scilimits=(0,0))

plt.xlabel('%s [%s]' %(XUnitName, XUnitLetter))
plt.ylabel('%s [%s]' %(YUnitName, YUnitLetter))
plt.title('good figure')


#%%
plt.figure(3)
if XSmartFormat:
	XToUse, XScaleLetter = Units.GetAxisSI(x)
else:
	XToUse = x
	XScaleLetter = ''
	


YToUse = y
	
plot(XToUse, YToUse)

plt.xlabel('%s [%s%s]' %(XUnitName, XScaleLetter, XUnitLetter))
plt.ylabel('%s [%s]' %(YUnitName, YUnitLetter))
plt.title('even better figure: we have unit letters on x')

#%%
plt.figure(4)
if XSmartFormat:
	XToUse, XScaleLetter = Units.GetAxisSI(x)
else:
	XToUse = x
	XScaleLetter = ''
	


if YSmartFormat:
	YToUse, YScaleLetter = Units.GetAxisSI(y)
else:
	YToUse = y
	XScaleLetter = ''
	
plot(XToUse, YToUse)

plt.xlabel('%s [%s%s]' %(XUnitName, XScaleLetter, XUnitLetter))
plt.ylabel('%s [%s%s]' %(YUnitName, YScaleLetter, YUnitLetter))
plt.title('we overdid: we have wrong scale Letter on y')

```

**Comment by aljosahafner** [comment]
I started checking this ...

**Comment by aljosahafner** [comment]
It will be quite difficult to make the unit conversion in the plots, because it seems that the unit is fixed by the welcome window. What I propose is to implement scientific notation as a number format.

**Comment by capitanevs** [comment]
What does this exactly mean?

The "welcome window" just fixes the lengths (and for SHADOW).

But what if we wanted to plot something that it is not a lenght but another quantity? For instance degrees? I guess that  there must be the chance  to write "deg", or "rad" or "mrad".

What do you mean with that?

> hat I propose is to implement scientific notation as a number format.

If you have any smarter solution it is very welcome.

The Unit Module does a stupid/simple thing: you give him an array full [of 0.0001, 0.0002....] and it returns an array with [100, 200,...] + a string "u" that you should append to the legend.

**As an alternative, EngNotation (values in the form xe-3, xe-6 etc) is also excellent, so if you have hands on, go for it.**

What I would like to avoid is "free" exponential notation, where you have exponent non-multiple of 3.

I wrote it quickly, so please tell me if I was not clear.

**Comment by aljosahafner** [comment]
I agree with all the above. 

That's why I implemented a more complicated, but complete solution. I split the `xtitles` which previously contained both the quantity name (e. g. `S`) and unit (e. g. `mm`) into `xtitles` and `xunits`. 
Before plotting I use two functions from the `LibWiser.Units` module, namely the `Units.GetEngPrefix` and `Units.GetEngFactor`. 
The plotting data for `x` is multiplied by:
`xData = xData * 1/xPrefix`

The xtitle is then constructed as:

`xtitle = xtitles[index] + " [" + xprefix + xunits[index] + "]"`

This is implemented in version `0.2.19`

**Comment by aljosahafner** [comment]
![image](https://user-images.githubusercontent.com/51963146/122914231-b5782780-d35a-11eb-91d1-eeb2662913dc.png)
![image](https://user-images.githubusercontent.com/51963146/122914264-bf018f80-d35a-11eb-86fe-3d3558a7c7d0.png)
![image](https://user-images.githubusercontent.com/51963146/122914287-c759ca80-d35a-11eb-8070-64344a16f4b2.png)

**Comment by aljosahafner** [comment]
A problem I can see is that I take `xPrefix` and `xScale` from first element of the array:

`xPrefix = Units.GetEngPrefix(xData[0])`

`xScale = Units.GetEngFactor(xData[0])`

**Comment by capitanevs** [comment]
Yes, you are right.

I tried to solve the problem by means of the function
`GetAxisSI(x)`

which already returns an array + the unit (and we can add other things if needed)
![immagine](https://user-images.githubusercontent.com/13431660/122918954-fa528d00-d35f-11eb-85c3-165dd637ce2e.png)


This function actually call an intermediate function that returns many more information (but not the rescaled x axis)

![immagine](https://user-images.githubusercontent.com/13431660/122919076-2110c380-d360-11eb-8a89-d7f47caec644.png).

**Such a function contains the "intelligence" for getting the "good" scale** (i.e. what you did by picking the first element).

Before I used to get the mean value. Then I realized that the mean value of an array ranging from -a to a is zero :-)

So now I selected the "maximum" value

![immagine](https://user-images.githubusercontent.com/13431660/122919401-7b118900-d360-11eb-9670-4aabab4b1073.png)


You may consider to use `GetAxisSI` so that we have a unique point where we control the  unit scale selection.

**Comment by aljosahafner** [comment]
Great! I changed to using `Units.GetAxisSI` in `v0.2.20`:

`xPlot, xPrefix = Units.GetAxisSI(xData)`

When tested and this issue is closed, I will bump the version to `v0.3`

**Comment by capitanevs** [comment]
Ok, Thank you.

I have quickly rewritten Units.py, but if you use GetAxisSI al that should be transparent for you.

**Comment by capitanevs** [comment]
The smart formatting is completed.
I will close this issue (closing issues is always great!).

In case we encountered new problems with this, we will open(re-open) an issue

**Comment by aljosahafner** [comment]
I will bump the version to `v0.3` in the next iteration
