### ISSUE TITLE
FigureError : check

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#50]
Hey,

I saw you have been changing some things around the figure error handling in Foundation. It seems that something doesn't work with the latest LibWiser.

![immagine](https://user-images.githubusercontent.com/13431660/113156648-78f4ce00-923a-11eb-9b19-75b418eabe44.png)

I am getting this error when using ldm-kbh/Scan_Motor5_55_res.dat file with ELETTRA-LTP-JAVA1 setting. I am almost 100% that this is due to an upgrade in LibWiser, since the propagation works normally without figure error and I saw there were some changes recently.

Cheers,
Aljosa

**Comment by aljosahafner** [comment]
Even after bumping the version, the problem persists
![image](https://user-images.githubusercontent.com/51963146/121372353-83b89700-c93e-11eb-9396-670b7fc34db4.png)

**Comment by capitanevs** [comment]
Good,
We ll get it.
Thank you for noticing.
M
--
Inviato da myMail per Android Mercoledì, 09 Giugno 2021, 04:20PM +02:00 da aljosahafner  ***@***.*** :

**Comment by capitanevs** [comment]
From the last joint session, it turned that - at a certain point - Aljosa's oasys started working.

We need one more one session to establish what is really going on.

In the meanwhile, the figure error can be manually load via python script, if need be.
