### ISSUE TITLE
To understand: Maintenability

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#51]
I needed some new functionalities of my local version of LibWiser, so to make it shorter I thought it could be possible
just to substitute my files (Foundation.py etc) into the folder of miniconda.

This was not possible:
apprantelry, this prevented Oasys to recognize the widged, and the widget were not loaded (not only in the ow space, but also in the menu).

Probably this is a "feature", not a bug.
But as it is unexpected (to me, maybe not for you), I would like to know a little bit more on that.

Any comments?

**Comment by capitanevs** [comment]
In any case, for better debugging OASYS-WISER, it would be easier if I could use the last version of LibWiser.

Can we find a pipeline for that?

**Comment by aljosahafner** [comment]
This can be done by running 

`python3 setup.py sdist develop`

prior to running Oasys from the correct venv.
