### ISSUE TITLE
Slit widget is broken?

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#56]
We have won a new bug
![immagine](https://user-images.githubusercontent.com/13431660/126292721-f37df2cd-ce3a-4950-b413-eb5b2a8b7993.png)

by the way, it is physically correct that "Slits" has no figure error :-) What has happened?

**Comment by aljosahafner** [comment]
I have no clue... This is new, I haven't changed anything

**Comment by capitanevs** [comment]
Yep, I suspected it.
Maybe I did :)
--
Inviato da myMail per Android Mercoledì, 21 Luglio 2021, 10:02AM +02:00 da aljosahafner  ***@***.*** :

**Comment by capitanevs** [comment]
The "Slits" optical element properli works in LibWiser.

The codes below (.py and .ow) represent the same layout, but error arises in .ow.
The topic should be investigated.


Beamline as seen in LibWiser
```
====================
Beamline Name:

*[s]*           (I), dZ=0.00 m, Z=0.00 m, (I), Lambd=50 n, Waist=1 f, M2=1 
*[slits_v]*     (V), dZ=50.00 m, Z=50.00 m, (V), L=1 m, <-->
*[det_v]*       (V), dZ=100.00 m, Z=150.00 m, (V), L=50 m
====================
```
Beamline as seen in OASYS

![immagine](https://user-images.githubusercontent.com/13431660/130446355-10656d5f-6912-4668-b285-95bee38be44e.png)

[test_slits_simple.RENAME_AS_PY.txt](https://github.com/oasys-elettra-kit/OASYS1-Wiser/files/7031869/test_slits_simple.RENAME_AS_PY.txt)

[diffraction from slits_rename_as_OWS.txt](https://github.com/oasys-elettra-kit/OASYS1-Wiser/files/7031863/diffraction.from.slits_rename_as_OWS.txt)

**Comment by aljosahafner** [comment]
I updated to the newest version of LibWiser, but the error persists. I will investigate in these days.

**Comment by aljosahafner** [comment]
Bug fixed in `0.3.2`. There has been code in `OWOpticalElement` which is the parent element also for `OWSlits`. It was checking for `CoreOptics.FigureErrors`. I added another if sentence to skip that part of the code.

**Comment by capitanevs** [comment]
Ok, the figure error now works properly.

Q: which kind of sentece did you use? an `if`, a `try`?

The question arise from the fact that OWOpticalElement is generic, so it should not contain something very specific like `if type(...) is Optics.Slits then SKIP`, but something more generic like a `try` or a `if ... has figure error`.

**Comment by capitanevs** [comment]
**One more fix**: GrazingAngleNominal as it appears in the GUI and as it appears in LibWiser does not match.

Perhaps such a parameter is not present in`OWOpticalElement` and requires extra coding?
If so, I would reccomend to create an intermediate `OWOpticalNumerical` that can be used for a wide class of optical element, sharing the same parameters. Even if those parameters are not so many, we would avoid missteps. => to be discussed


![immagine](https://user-images.githubusercontent.com/13431660/130648561-ac12a1e4-ad6a-445c-8f16-df2ebe074a34.png)

**Comment by aljosahafner** [comment]
> Ok, the figure error now works properly.
> 
> Q: which kind of sentece did you use? an `if`, a `try`?
> 
> The question arise from the fact that OWOpticalElement is generic, so it should not contain something very specific like `if type(...) is Optics.Slits then SKIP`, but something more generic like a `try` or a `if ... has figure error`.

You're right, I changed the `if` sentence to check for the property `FigureErrors`:

`if hasattr(native_optical_element.CoreOptics, 'FigureErrors'):`

**Comment by aljosahafner** [comment]
> **One more fix**: GrazingAngleNominal as it appears in the GUI and as it appears in LibWiser does not match (2deg vs 1.57rad=90deg, which is the default value)
> 
> Perhaps such a parameter is not present in`OWOpticalElement` and requires extra coding?
> If so, I would reccomend to create an intermediate `OWOpticalNumerical` that can be used for a wide class of optical element, sharing the same parameters. Even if those parameters are not so many, we would avoid missteps. => to be discussed
> 
> ![immagine](https://user-images.githubusercontent.com/13431660/130648561-ac12a1e4-ad6a-445c-8f16-df2ebe074a34.png)

This really shouldn't be an issue, maybe it just wasn't refreshed yet, this is to be rechecked definitely!

**Comment by aljosahafner** [comment]
> **One more fix**: GrazingAngleNominal as it appears in the GUI and as it appears in LibWiser does not match (2deg vs 1.57rad=90deg, which is the default value)
> 
> Perhaps such a parameter is not present in`OWOpticalElement` and requires extra coding?
> If so, I would reccomend to create an intermediate `OWOpticalNumerical` that can be used for a wide class of optical element, sharing the same parameters. Even if those parameters are not so many, we would avoid missteps. => to be discussed
> 
> ![immagine](https://user-images.githubusercontent.com/13431660/130648561-ac12a1e4-ad6a-445c-8f16-df2ebe074a34.png)

Yes, my mistake. I haven't linked the `AngleGrazing` in Oasys. Now it works!

**Comment by capitanevs** [comment]
Bug fixed.

Let's consider for the future the strategy of "SharedParameters/UniversalPArameters", etc.
