### ISSUE TITLE
Reduce the number of warnings

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#58]
Would you help me remove  this warning?
It is a fake one, I guess we just have to shut down the warning level.

![immagine](https://user-images.githubusercontent.com/13431660/130958864-692dea4b-6d18-4d25-ad37-56a47c5b3b94.png)

The current version of LibWiser on git is the newest one.

**Comment by aljosahafner** [comment]
I guess this arises due to lines 896:
`NP =   Oversampling * len(P)-1 # degree of the polynomial`

and 916:
`P_new = np.polyfit(px_new, py_new, NP)`

`NP` is too high for the number of points. Do you think it's fake and just needs to be suppressed or should we change line 896 to something else in order not to be overfitting by numpy standards.

**Comment by capitanevs** [comment]
This is something I encountered at day 3 of wiser, and I have never understood.
In principle I am fitting N points with a polynomial of lower degree (Np<N)  so I expected it to be ok.
If you have more advance mathematical skills and want do to a quick check, it's very welcome.
Otherwise let's just find the way to shut it off. Results always seemed to be consistent.
--
Inviato da myMail per Android Giovedì, 02 Settembre 2021, 08:08AM +02:00 da aljosahafner  ***@***.*** :

**Comment by aljosahafner** [comment]
If it works, then I think it's best to just suppress the warning.

**Comment by aljosahafner** [comment]
Ok, I suppressed the warning, line 885:
`warnings.simplefilter('ignore', np.RankWarning)`

**Comment by capitanevs** [comment]
great! one issue less. We are effective:-)
--
Inviato da myMail per Android Giovedì, 02 Settembre 2021, 09:20AM +02:00 da aljosahafner  ***@***.*** :
