### ISSUE TITLE
"UseAsReference" tag is cumbersome, in OASYS?

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#60]
I happened to waste 30min because of the "Reference" behavior that I used for slits.

When it is meant to be useful:
- When you want to add them within an existing beamline, the distances are expressed mostly referring to the "upstream"element and one does not want to change this values.
=> Possible solution: use absolute positioning

When it is dangerous:
-in OASYS, almost always, since it is not told anywhere about this behavior.

**What to do?** (MM)
a) change slits attribute in LibWiser
OR
b) add a disclaimerin the GUI

**Comment by aljosahafner** [comment]
You're right, it's completely ignored for now and always takes default behaviour. We can either:
- add a tick box (Reference element)
- discuss other options

**Comment by capitanevs** [comment]
The tick box would be definitely the best idea.

The problem is that now `UseAsReference` is an an argument of the init functions (e.g.  `a = MirrorElliptic(...., UseAsReference=True)`), but it is hardcoded in the `init` function.

To apply a tickbox `Use as reference: {True(Default)|False}` to all the elements,refactoring is needed.

An alternative would be applying the tickbox to slits only.

We can discuss that on monday.

Question: if we are changing the widget for the optical element, will be able to read the existing ows file (with the right parameters), or not? **Can we make a try?**



 
-

**Comment by aljosahafner** [comment]
Good point! We need to be careful about that yes.

Since Slits is the only one which doesn't have the default (True) behaviour I could add it only there. Should I wait or add it now?

**Comment by capitanevs** [comment]
Let's make a try, just to test how the save/restore works.
Let s add it to slits only, an see how it behaves:)
Label: Use as reference = yes(default)/no. 
You can use also a list box like that one of ignore.
I have just commited. Then I will be out of officr for 1hr.
Tnx! 
Michele
--
Inviato da myMail per Android Mercoledì, 01 Settembre 2021, 11:06AM +02:00 da aljosahafner  ***@***.*** :

**Comment by aljosahafner** [comment]
Ok, I added a similar style box as with `ignore`.

**Comment by capitanevs** [comment]
Checked.

The new box :
-DOES NOT create problems with save/load feature, neither on slit widget nor on other widgets (good!).
-properly works :-)

I'll close the issue. 
Reopne: when/If ready to extend this box to OWOpticalElement.
