### ISSUE TITLE
OASYS Error Log  window

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#65]
My error log window is always blank...... this is happening since a while, but I was just convinced there were no errors :-)

Can the suppression of the warning that we put in LibWiser be related to that?

![immagine](https://user-images.githubusercontent.com/13431660/133764024-d0cd6efd-9975-40c5-8eab-bfa0675e0e05.png)

**Comment by aljosahafner** [comment]
I don't know about this, sorry...

**Comment by capitanevs** [comment]
Ok tnx.
Two questions:
1) since the output is broken, I need a popup window to cast custom warning messages. Can you give me any lines of code which is doing that (and the needed module)? I guess that of oasys is good

2) All the exception raised on purpose in LibWiser are automatically intercepted and casted as "pop up messages" in oasys, right?

**Comment by capitanevs** [comment]
Still pending, but not serious.

Can be closed (next meeting)
