### ISSUE TITLE
Plot formatting

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#68]
Reduce the number of digits.

![immagine](https://user-images.githubusercontent.com/13431660/135054824-c9a1e330-a594-490f-af5a-af81edd960ef.png)

Hint:
try to use one of the following formatting function of libwiser. You can create a oasys port somewhere, to decouple from libwiser, if you wish.

The code below is from the docstring of LibWiser.Units
```

Examples
------
x = 0.1e-9

GetEngInfo(x)
>>> {'SIMant': 1.0, 'SIPow10': -9, 'SIPrefix': 'n', 'EngMant': 1.0, 'EngPow10': -9}


GetFormattedEng(x)
>>> '1e-9'

GetFormattedSI(x)
>>> '1 n'



SmartFormatter(x)
>>> '1 n'


SmartFormatter(x, {'unit' : 'm'})
>>> '1 nm'


import numpy as np
x = np.linspace(-1e-6, 1e-6, 5)
GetAxisSI(x)
>>> (array([-1. , -0.5,  0. ,  0.5,  1. ]), 'u')
```

**Comment by aljosahafner** [comment]
Ok, good call! I corrected all the titles and messages in `OWDetector` to use `LibWiser.Units.SmartFormatter` function. The changes are implemented in `0.3.13`.
