### ISSUE TITLE
IGNORE => Is the Gui badly connected? (Yes)

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#72]
Also here, it seems that the gui and the internal representation of the beamline do not match.

Can you please do a round check of all the controls of the GUI and check that they properly send their data to LibWiser?

![immagine](https://user-images.githubusercontent.com/13431660/135540618-6758043a-a01f-401f-a05a-1b86c3a8c0c2.png)

Hint:use the GetBeamline python script to check.

**Comment by capitanevs** [comment]
If the slit is NOT ignored, then a detectorplaced downstream will show a diffraciton pattern
![immagine](https://user-images.githubusercontent.com/13431660/135540833-e783babf-b61e-48eb-bc4e-c5a62d76bd2e.png)


If the slit is IGNORED, then a detector will just show the propagated gaussian intensity from the source

![immagine](https://user-images.githubusercontent.com/13431660/135540908-cad9e7e5-3380-4769-bb95-cf4071fa24d7.png)


We are physicist,not programmers :-) Let's check physics, too...

**Comment by aljosahafner** [comment]
Ignore option works in the following way:
`libWiserOE.CoreOptics.ComputationSettings.Ignore = (self.ignore == 1)`

**Comment by capitanevs** [comment]
It's wrong

There is no `Ignore` attribute into `CoreOptics.ComputationSettings`

Use
`libWiserOE.ComputationSettings.Ignore`, instead.

**Comment by aljosahafner** [comment]
I am already using 

`libWiserOE.ComputationSettings.Ignore`

![image](https://user-images.githubusercontent.com/51963146/145378675-828a7de5-25c2-46a5-ac2b-5226c046e4fd.png)

**Comment by capitanevs** [comment]
Nope,
you are using
`libWiserOE.CoreOptics.ComputationSettings.Ignore`
while the correct one is
`libWiserOE.ComputationSettings.Ignore`

:-)

**Comment by aljosahafner** [comment]
You're right, my bad :D I'll proceed with updating immediately

**Comment by aljosahafner** [comment]
I think it's ok... `0.3.18` should have it the proper way.

**Comment by capitanevs** [comment]
Let's close it.
