### ISSUE TITLE
Issue from Users: Rotations

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#75]
A user just complained that "rotation", "transverse displacemente" within the displacement tab are no longer working.

We should not have changed them, and for sure they were working (as these people made a paper using these very old-dated features, so I guess they know what are talking about :-)

Can we check that they are properly linked from the GUI for ALL the elements (e.g. source, plane mirror, ellipsoidal mirror, detector)? Lately, we had some "GUI-link" issues, even if they were on new stuff (not old one). I guess.... it could be better to have a look.

At the same time, I will check that everything is ok on the library.

**Comment by aljosahafner** [comment]
I haven't changed anything at all. If I remember correctly, these were checked just a few months ago and they were working. Can you specify a bit better what is not working, which widget, etc.

* Source has the small displacements set in its own file: `ow_gaussian_source_1d.py` (lines 182 to 188)
* The rest of the elements have it in `ow_optical_element.py` (lines 540 to 546)

**Comment by capitanevs** [comment]
We still have no all infos, but I guess the problem is on the "plane mirror". so in ow_optical_element.py.

Looking at the code, does it seems all ok to you?

**Comment by aljosahafner** [comment]
The code for elements seems all ok for me, the question is whether everything works well in the library using setting:
* `self.rotation`
* `self.transverse`
* `self.longitudinal`

All the optical elements widgets inherit from OWOpticalElement (`ow_optical_element.py`)

**Comment by capitanevs** [comment]
Note1:

Design error:
while writing "Slits" in LibWiser, the code was re-written from the Mirror Class (instead of using subclassing, inheritance).

Some important features which are present in Mirror, are not in slits (e.g. the SmallDisplacements)


![immagine](https://user-images.githubusercontent.com/13431660/144769381-ad80fa6f-49e7-4155-8549-bce1d2c4e5ea.png)

![immagine](https://user-images.githubusercontent.com/13431660/144769390-816d0c60-8fea-4241-b1e4-56cc303780be.png)

**Comment by capitanevs** [comment]
Temporary solution:
I just short-linked the twofunctions 
![immagine](https://user-images.githubusercontent.com/13431660/144769681-49f5b7d3-7ef6-44a1-9a22-92dd8e1cd459.png)

**Comment by capitanevs** [comment]
Error Found in LibWiser (shame on me)

![immagine](https://user-images.githubusercontent.com/13431660/144769952-71d1f748-4a77-403a-bff8-3f794cef80ab.png)

`xLab` appears instead of `xNew` (the same for y)

**Comment by capitanevs** [comment]
After fixing the previous bug, I see that
- The profile of the mirror is correctly changed
- The position of the beam on a downstream element (slits in this case) does not change.
Suspicious...

![immagine](https://user-images.githubusercontent.com/13431660/144770519-e32263a8-8f09-4e85-bc1d-e7c529686725.png)

**Comment by capitanevs** [comment]
The rotation angle affects somehow the computation (even if not as I would like to). If the angle is too high, aliasian occurs

![immagine](https://user-images.githubusercontent.com/13431660/144770541-143d83ac-0425-4738-aa70-da538d177e82.png)

**Comment by capitanevs** [comment]
Remember: now we have the two kind of output rays: nominal and real (it is not a problem, but I just point it out for me)
![immagine](https://user-images.githubusercontent.com/13431660/144770645-a0424446-018e-4b28-9e10-eb69205a66cb.png)

**Comment by capitanevs** [comment]
In the previous computations I used Rotation angles which were too big:
angle * distance = displacement which was much greater than the size of the target element (the slits). Displacement was about 8 meters ( it should me mm).

In principle, what I expected to see was: flat or noisy field.
ButI still could see the beam => why? strange aliasing effect?

Using meaningful Rotation angles I get correct results:

![immagine](https://user-images.githubusercontent.com/13431660/144802584-49411bb5-4ced-42e7-939a-3e26fd58b380.png)

**This is good**

**Comment by aljosahafner** [comment]
Is it ready to be implemented in OasysWiser?

**Comment by capitanevs** [comment]
I close the issue. 
I will reopen it if something is wrong.

**Comment by aljosahafner** [comment]
Can I update LibWiser on PyPI and therefore in OasysWiser?
