### ISSUE TITLE
Question on Numb

### ISSUE THREAD

**Issue by capitanevs** [oasys-elettra-kit/OASYS1-Wiser#80]
I get this warning.

Does it happens to me only?

![immagine](https://user-images.githubusercontent.com/13431660/164025900-1e16ac37-514a-4711-b815-a4db4220e0c9.png)

**Comment by aljosahafner** [comment]
It's the first time I see it, as far as I see it's just a warning.

**Comment by capitanevs** [comment]
do 
conda install tbb
