### ISSUE TITLE
Numerical source/Cross-link with SRW

### ISSUE THREAD

**Issue by aljosahafner** [oasys-elettra-kit/OASYS1-Wiser#9]
Placeholder for numerical source issue... @maltissimo @capitanevs

**Comment by maltissimo** [comment]
Hello, I started digging into the code to get out the data needed. I do not know how you guys store the electric field. In any event this is how I got thus far: if you run and SRW undulator source in OASYS, then connect a python script widget:

>>> srw_beam=in_object_1

>>> print(dir(srw_beam))

['_SRWData__srw_beamline', '_SRWData__srw_wavefront', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'get_srw_beamline', 'get_srw_wavefront', 'get_working_srw_beamline', 'reset_working_srw_beamline', 'set_working_srw_beamline']
>>> srw_wf=srw_beam._SRWData__srw_wavefront

>>> print(dir(srw_wf))
['Rx', 'Ry', 'ScanningData', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'addE', 'allocate', 'arElecPropMatr', 'arEx', 'arEy', 'arMomX', 'arMomY', 'arWfrAuxData', 'avgPhotEn', 'calc_stokes', 'copy_comp', 'dRx', 'dRy', 'decorateSRWWF', 'delE', 'duplicate', 'fromGenericWavefront', 'get_1D_intensity_distribution', 'get_2D_intensity_distribution', 'get_dimension', 'get_flux', 'get_intensity', 'get_intensity_from_electric_field', 'get_phase', 'get_photon_energy', 'get_wavelength', 'mesh', 'numTypeElFld', 'partBeam', 'presCA', 'presFT', 'scanned_variable_data', 'setScanningData', 'toGenericWavefront', 'unitElFld', 'unitElFldAng', 'xc', 'yc']


These are all the methods available. Their definitions sits in srw_wavefront.py, which in turns is: wofrysrw.propagator.wavefront2D

Inside there, there are methods for converting wavefronts between numpy-digestible and SRW-data: 
SRWEFieldAsNumpy
SRWWavefrontFromElectricField
numpyArrayToSRWArray
SRWArrayToNumpy


Please do tell me if this helps, or if you need further info.

**Comment by capitanevs** [comment]
Thanks, very helpful

Do we need a source only, or a source + a "continuation plane"? Can you also provide an example file, with a configured test source?

I do not work on OASYS-GUI right now, so I will need someone's assistance to extract the field. 

@aljosahafner: can you do that, just throwing out a .txt? Guess that `np.savetxt('outfile.txt', MyArray.view(complex))` would be fine. I think that the candidate function is `SRWEFieldAsNumpy`. Let's start with a distance of... 5m from the source.

Thanks.

**Comment by maltissimo** [comment]
You cannot have a source without a continuation plane: SRW calculates the field at a certain, specified distance. See attached ows file. 
[SRW field data extraction.ows.zip](https://github.com/oasys-elettra-kit/OasysWiser/files/4515448/SRW.field.data.extraction.ows.zip)

**Comment by aljosahafner** [comment]
After being generated (through GUI or script), the wavefront is accessible as:

`import wofrysrw

srwData = in_object_1
srwWavefront = srwData._SRWData__srw_wavefront

efield = np.array(srwWavefront.arEx) # 1D array of E field with real, imaginary, real, etc. components

dim_x = srwWavefront.mesh.nx # Number of points - sampling
dim_y = srwWavefront.mesh.ny

re = np.array(efield[::2], dtype=np.float)
im = np.array(efield[1::2], dtype=np.float)

e = re + 1j * im # Make the array out of real and imaginary components 
e = e.reshape((dim_x, dim_y)) # If necessary, reshape into a regular grid

asNpy = wofrysrw.propagator.wavefront2D.srw_wavefront.SRWEFieldAsNumpy(srwWavefront)[0][0, :, :, 0] # Access single wavelength, single polarization from the 4D array`

**Comment by capitanevs** [comment]
**I inspected a little bit SRW data.**

All the intensity profiles
![immagine](https://user-images.githubusercontent.com/13431660/122354483-5462e500-cf51-11eb-9f86-56fd3c0c84d8.png)

The averaged Intensity
![immagine](https://user-images.githubusercontent.com/13431660/122354558-63e22e00-cf51-11eb-9c36-9cc1cafa2f9b.png)


This seems to be what is shown in the "screen" widget.

![immagine](https://user-images.githubusercontent.com/13431660/122354616-752b3a80-cf51-11eb-8433-bd8536e84464.png)

**I need info on what the widget that converts from 2D  wavefront <--> 1d wavevront** does. (**by the way, where is it?**).

**As a general concept** I guess it ahs the following parameters
- direction of the slice (typically H or V, an angle could be also possible but it is not really necessary now)
- HOW to compute the Modulus of the slice a) get the central slice only, b)average on few (central slice), c) average on alla the slices.
- HOW to compute the Argument  of the slice: the same a), b), c) as before, but non necessarily locked with each other (at least during tests). 
- Else?

**Comment by aljosahafner** [comment]
2D wavefront -> 1D wavefront widget is a part of Wofry widgets Tools package: https://github.com/oasys-kit/OASYS-WOFRY/tree/master/orangecontrib/wofry/widgets/tools

**Comment by capitanevs** [comment]
Ok, to complete the link b\w SRW and WISER we need the long awaited SourceNumeric. This is what I have in mind:
![immagine](https://user-images.githubusercontent.com/13431660/123293435-45150600-d514-11eb-9913-835feeb30a49.png)

I don't think we can plug "wofry2wiser" directly to wiser. WISER does need a "source" and I would be quite surprised if the direct link wored.

**Comment by capitanevs** [comment]
I have implemented SourceNumeric in Optics.py
![immagine](https://user-images.githubusercontent.com/13431660/123294149-dedcb300-d514-11eb-96d9-7fd41a2566e9.png)


And its usage is (for example)
![immagine](https://user-images.githubusercontent.com/13431660/123294839-7e9a4100-d515-11eb-83c3-0fb20847d106.png)



The novelty is line88.

The present design of LibWiser is such that CoreOptics contain the geometric information and OpticalElement contains ComputationData, where the field is stored. A posteriori this is not that great, but line 88 just fills the computation data in the right way.

I am not still sure that it works PERFECTLY, but it runs and it returns nice plots

![immagine](https://user-images.githubusercontent.com/13431660/123294613-4c88df00-d515-11eb-858d-48ced496b4a2.png)


When you have time, can you start drafting the widget **Numerical Source?**

It can work in two ways:
- by loading data from file
- by getting data from the chain (from wofry2wiser)

I would prioritize the second, leaving just disabled input for the file.

What do you think?

**Comment by aljosahafner** [comment]
Please go through the code of the Wofry to Wiser widget a bit, there is a creation of a Dummy source in between.
* Wofry -> Wiser: https://github.com/oasys-elettra-kit/OASYS1-Wiser/blob/master/orangecontrib/wiser/widgets/tools/ow_from_wofry_wavefront_1d.py
* Wiser -> Wofry: https://github.com/oasys-elettra-kit/OASYS1-Wiser/blob/master/orangecontrib/wiser/widgets/tools/ow_wise_wavefront_to_wofry.py

**Comment by capitanevs** [comment]
Very interesting.
Apparently Luca created a LibWiser-like DummyElement  that subclasses the GaussianSource and has a specific function for evaluating the field.
This is  very good.
However I do not expect it is gonna work: GaussianSource subclasses OpticsAnalytical, whereas here we need an OpticsNumerical. The propagation manager (in LibWiser) behaves in two different ways accprding to the kind of optical element.
I guess that just by replacing SourceGaussian with SourceNumerical we can get things (almost) done.
Shall we try?
M
Sidenote: for how Luca's code is done, DummyElement could inherit from any numerical optical element, e.g. a Mirror or tthe detector.

--
Inviato da myMail per Android Venerdì, 25 Giugno 2021, 09:05AM +02:00 da aljosahafner  ***@***.*** :

**Comment by capitanevs** [comment]
So, if we link wofry2wiser---> Wiser detector we get something, but we should understand what.

![immagine](https://user-images.githubusercontent.com/13431660/123622300-5d369f00-d80c-11eb-8181-281fcaab3ec5.png)

![immagine](https://user-images.githubusercontent.com/13431660/123622343-67589d80-d80c-11eb-9887-61512411d24a.png)

![immagine](https://user-images.githubusercontent.com/13431660/123622366-6de71500-d80c-11eb-94fb-9a7b3b487067.png)

**Comment by capitanevs** [comment]
Comment 1

The behavior of an optical element which is place at "0 distance" from the previous one does not appear to be so well defined in LibWiser

![immagine](https://user-images.githubusercontent.com/13431660/123638644-b2c87700-d81f-11eb-95f5-44a0cb578add.png)

![immagine](https://user-images.githubusercontent.com/13431660/123638681-bb20b200-d81f-11eb-9a7e-450850bc9fd0.png)

![immagine](https://user-images.githubusercontent.com/13431660/123638735-ca076480-d81f-11eb-8df7-03aa0d9a4ded.png)


A still different behavior occurs if the positioning method is chosen.

This can not be a problem in the 95% of cases, since there is no need to put a detector at 0 distance from an optical element.

The first case I have encountered is the case of a "numeric source" (or wofry surce), where it comes as spontaneous to put a wiser detector widget downstream wofrywise widget, to see what is going on.

**Comment by capitanevs** [comment]
Comment2)
How do we want wiser to be have with a layout like this? (probably nothing)

![immagine](https://user-images.githubusercontent.com/13431660/123642718-e73e3200-d823-11eb-9664-599b9134ef17.png)

The reason of this (apparently) is simple: to make an effective test of the numerical source we would need the following layout

Source ---->detector ---->save field

load field --->numerical source ----> beamline

and compare it with

Soure --->beamline

(if not clear, I will explain it orally)

**Comment by capitanevs** [comment]
I see that there are writers and readers for wavefronts in wofry 

![immagine](https://user-images.githubusercontent.com/13431660/123643246-7a776780-d824-11eb-8420-735b4b2fe271.png)


Probably this is al what we need.

**Comment by capitanevs** [comment]
```
1. Wiser Numerical source is not tested yet
2. the best way to test it is in oasys: this needs to wire some tools =>
	in principle wiser2wofry+wofry_write + wofry read + wofry2wiser should be all that we needs
	

2b: once the pipeline is ok, we can play with making a gaussian source numerical, then propagate it, and check the differences.

3. In principle it would be nice if we had an "all wiser" numerical source with access from file
	=> the advantage is the auto-generation of wiser code (supported at 80%)
	
	BUT
	
	This is not a priority
	
	BUT
	
	Let's keep this in mind.
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	Field = sqrt(Intensity) * exp(1j*phase)
	
	
	def get_numerical_source(wofry_wavefront):
    
    
    
    Lambda = wofry_wavefront.get_wavelength() % => check the units
    
    L = wofry_wavefront.get_size() # checl
    
    Field = sqrt(wofry_wavefront.get_intensity()) * exkp(1j * wofry_wavefront.get_phase())
    
    # build the Numerical source here
    
     WiserNumericalSource = OpticalElement(
                                CoreOptics.SourceNumerical
                                    (....
                                    ...)
                                 PositioningDirectives(     )
                                 
                                 # CAUTION!: where to put the numerical source?
                                Numerical sources are not set at the waist z=0, but a little bit downstream, e.g. z=5 (numerical reasons).
                                This means that all the distances are offsetted.
                                CONSEQUENCE => we need to introduce an extra field called "Virtual Offset" or "Offset to real source waist" 
                                (suggestions on naming are welcome) that is then used by all the functions computing the distances 
                                in LibWiser I am doing it now
                                
                                This also means that we need a new field in the conversion widget. Without this, all the distances would be screwed up.
    




    
    return Foundation.OpticalElement(Name="Wofry Source",
                                     IsSource=True,
                                     CoreOpticsElement=DummyElement(wofry_wavefront=wofry_wavefront),
                                     PositioningDirectives=Foundation.PositioningDirectives(ReferTo=Foundation.PositioningDirectives.ReferTo.AbsoluteReference,
                                                                                            XYCentre=[0.0, 0.0],
                                                                                            Angle=0.0))
```
